// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aoluujxnktxcjtcbmczt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbHV1anhua3R4Y2p0Y2JtY3p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTQ5NzUsImV4cCI6MjA2NTQ5MDk3NX0.lp0VfDGcMuPSsAOKURBdZ-m8MhhhsSGTvrZqzRTcH9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);